# Generated by Django 5.2.9 on 2026-01-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0002_city_alter_review_comment_alter_review_comment_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='city_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='city_ru',
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ManyToManyField(related_name='city', to='house_app.city'),
        ),
        migrations.AddField(
            model_name='property',
            name='city_en',
            field=models.ManyToManyField(null=True, related_name='city', to='house_app.city'),
        ),
        migrations.AddField(
            model_name='property',
            name='city_ru',
            field=models.ManyToManyField(null=True, related_name='city', to='house_app.city'),
        ),
    ]
