# Generated by Django 5.2.9 on 2026-01-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0004_review_property_alter_city_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ManyToManyField(related_name='properties', to='house_app.city'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city_en',
            field=models.ManyToManyField(null=True, related_name='properties', to='house_app.city'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city_ru',
            field=models.ManyToManyField(null=True, related_name='properties', to='house_app.city'),
        ),
    ]
